repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

# Optional â€” re-enable Black later if needed
# -   repo: https://github.com/psf/black
#     rev: 25.9.0
#     hooks:
#     -   id: black

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.2
    hooks:
    -   id: clang-format
        exclude: |
          ^microros_ws/firmware/toolchain/
          ^\.local/
          ^\.cache/
          ^\.venv/
          ^env/
          ^build/
