planning_plugins:
  - ompl_interface/OMPLPlanner
request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision
start_state_max_bounds_error: 0.1

planner_configs:
  SBL:
    type: geometric::SBL
  EST:
    type: geometric::EST
  LBKPIECE:
    type: geometric::LBKPIECE
  BKPIECE:
    type: geometric::BKPIECE
  KPIECE:
    type: geometric::KPIECE
  RRT:
    type: geometric::RRT
  RRTConnect:
    type: geometric::RRTConnect
  RRTstar:
    type: geometric::RRTstar
  TRRT:
    type: geometric::TRRT
  PRM:
    type: geometric::PRM
  PRMstar:
    type: geometric::PRMstar

sekirei_arm:
  default_planner_config: RRTConnect
  planner_configs:
    - SBL
    - EST
    - LBKPIECE
    - BKPIECE
    - KPIECE
    - RRT
    - RRTConnect
    - RRTstar
    - TRRT
    - PRM
    - PRMstar
  projection_evaluator: joints(arm_joint1,arm_joint2)
  longest_valid_segment_fraction: 0.005
